<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jun Zhu Li">
<meta name="dcterms.date" content="2025-04-30">

<title>A Replication of Karlan and List (2007) – Jun’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-c9f0887447d3a639491f60c4af03832d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-dc376453fc93729a66e4175d27e645db.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jun’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:jzhuuli@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/junzhuli"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jun Zhu Li </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 30, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>To fully appreciate the importance and implications of this work, it is useful to examine the broader context in which the study was conducted, as well as the experimental methodology and key findings that emerged.</p>
<p>In the field of charitable fundraising, a persistent challenge faced by organizations is determining the most effective strategies to encourage donations. Historically, private giving in the United States has been robust, frequently surpassing 2% of GDP; however, fundraising practices have traditionally been guided more by anecdotal experiences and conventional wisdom rather than by rigorous empirical evidence. To address this gap, economists Dean Karlan (Yale University) and John List (University of Chicago) executed a pioneering field experiment aimed at empirically examining whether and how the “price” of giving influences charitable contributions.</p>
<p>Karlan and List’s research specifically focused on the “demand side” of charitable donations, an area notably under-explored relative to the tax-driven “supply side” incentives. The core research question guiding their investigation was whether reducing the effective cost of charitable donations through matching grants could successfully increase donor contributions. To empirically test this question, the researchers collaborated with a liberal nonprofit organization in the United States, utilizing a sample of 50,083 prior donors. These individuals were randomly assigned into two primary groups: approximately one-third constituted the control group, receiving a standard four-page fundraising letter, while the remaining two-thirds formed the treatment group, receiving a similar letter that prominently included an offer of a matching grant.</p>
<p>Within the treatment group, further randomization led to the creation of specific sub-conditions. These conditions varied by matching ratios (1:1, 2:1, or 3:1), maximum match amounts ($25,000, $50,000, $100,000, or an unspecified cap), and suggested donation amounts relative to donors’ previous contributions (100%, 125%, or 150%). The fundraising letters, distributed in August 2005, strategically referenced contemporary political events, specifically Supreme Court nominations, to ensure the real-world relevance and external validity of the study.</p>
<p>The results of Karlan and List’s experiment revealed compelling evidence regarding the efficacy of matching grants. The simple presence of a matching offer increased both the response rate by 22% and revenue per solicitation by 19%. Interestingly, however, increasing the match ratio beyond 1:1 to ratios of 2:1 or 3:1 yielded no additional incremental benefit. The findings suggest that the matching grants may have primarily acted as signals of credibility and urgency, leveraging social cues embedded in the framing of the match.</p>
<p>Additionally, the experiment found that variations in maximum match amounts and suggested donation benchmarks did not significantly influence donor behavior. Importantly, the study identified a notable contextual effect related to political environment: donors in politically conservative (“red”) states demonstrated significantly higher responsiveness to matching offers, with an increase of 55% in revenue per solicitation, whereas minimal effects were observed in politically liberal (“blue”) states. The estimated price elasticity derived from this experiment was approximately –0.225, aligning well with prior elasticity estimates from studies examining tax-based incentives.</p>
<p>This research provides clear implications for fundraising strategy and policy. Practitioners are advised that matching grants are effective tools, though escalating match ratios beyond a simple 1:1 offer may not be cost-effective or necessary. Moreover, the study challenges the conventional assumption that larger matching ratios inherently generate greater donor enthusiasm. Finally, the observed sensitivity to political and social context suggests that fundraisers must carefully consider these factors when crafting appeals.</p>
<p>Karlan and List’s seminal findings were published in their influential paper, “Does Price Matter in Charitable Giving? Evidence from a Large-Scale Natural Field Experiment,” appearing in the American Economic Review in 2007. Their supporting data are publicly accessible through the AEA Data Archive, Innovations for Poverty Action (IPA), and Harvard Dataverse, facilitating further academic scrutiny and replication studies.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<p>The dataset compiled by Dean Karlan and John List for their 2007 field experiment comprises 50,083 observations, each corresponding to an individual who had previously donated to a U.S.-based nonprofit organization. The data were collected to evaluate the effectiveness of different fundraising appeals and include detailed information on treatment assignments, donor responses, demographic characteristics, and contextual political variables. Approximately two-thirds of the sample were assigned to a treatment group that received a fundraising letter featuring a matching grant offer, with match ratios randomly varied across 1:1, 2:1, and 3:1 levels. The remaining third received a standard appeal letter and served as the control group.</p>
<p>Additional randomization was applied within the treatment group to vary the maximum matching amount ($25,000, $50,000, $100,000, or unstated) and the suggested donation amount based on the donor’s past giving behavior. The dataset includes binary indicators of whether a donation was made in response to the solicitation, the amount contributed, and the change in donation relative to previous behavior.</p>
<p>Furthermore, it contains socio-demographic and contextual variables at the ZIP code level, including average household size, median household income, homeownership rate, educational attainment, and the proportion of residents in urban areas. Political context is captured through indicators of whether the respondent resided in a red or blue state or county, based on the 2004 presidential election. This rich, multi-dimensional dataset enables rigorous analysis of causal effects in charitable giving, while also allowing for the exploration of heterogeneous treatment effects across geographic, political, and demographic lines.</p>
<div id="f044ee31" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_stata(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>df.describe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<pre><code>&lt;bound method NDFrame.describe of        treatment  control    ratio  ratio2  ratio3      size  size25  size50  \
0              0        1  Control       0       0   Control       0       0   
1              0        1  Control       0       0   Control       0       0   
2              1        0        1       0       0  $100,000       0       0   
3              1        0        1       0       0  Unstated       0       0   
4              1        0        1       0       0   $50,000       0       1   
...          ...      ...      ...     ...     ...       ...     ...     ...   
50078          1        0        1       0       0   $25,000       1       0   
50079          0        1  Control       0       0   Control       0       0   
50080          0        1  Control       0       0   Control       0       0   
50081          1        0        3       0       1  Unstated       0       0   
50082          1        0        3       0       1   $25,000       1       0   

       size100  sizeno  ... redcty  bluecty    pwhite    pblack  page18_39  \
0            0       0  ...    0.0      1.0  0.446493  0.527769   0.317591   
1            0       0  ...    1.0      0.0       NaN       NaN        NaN   
2            1       0  ...    0.0      1.0  0.935706  0.011948   0.276128   
3            0       1  ...    1.0      0.0  0.888331  0.010760   0.279412   
4            0       0  ...    0.0      1.0  0.759014  0.127421   0.442389   
...        ...     ...  ...    ...      ...       ...       ...        ...   
50078        0       0  ...    0.0      1.0  0.872797  0.089959   0.257265   
50079        0       0  ...    0.0      1.0  0.688262  0.108889   0.288792   
50080        0       0  ...    1.0      0.0  0.900000  0.021311   0.178689   
50081        0       1  ...    1.0      0.0  0.917206  0.008257   0.225619   
50082        0       0  ...    0.0      1.0  0.530023  0.074112   0.340698   

       ave_hh_sz  median_hhincome    powner  psch_atlstba  pop_propurban  
0           2.10          28517.0  0.499807      0.324528       1.000000  
1            NaN              NaN       NaN           NaN            NaN  
2           2.48          51175.0  0.721941      0.192668       1.000000  
3           2.65          79269.0  0.920431      0.412142       1.000000  
4           1.85          40908.0  0.416072      0.439965       1.000000  
...          ...              ...       ...           ...            ...  
50078       2.13          45047.0  0.771316      0.263744       1.000000  
50079       2.67          74655.0  0.741931      0.586466       1.000000  
50080       2.36          26667.0  0.778689      0.107930       0.000000  
50081       2.57          39530.0  0.733988      0.184768       0.634903  
50082       3.70          48744.0  0.717843      0.127941       0.994181  

[50083 rows x 51 columns]&gt;</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<div id="3d76fbbf" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>variables_to_test <span class="op">=</span> [<span class="st">'hpa'</span>, <span class="st">'freq'</span>, <span class="st">'years'</span>, <span class="st">'female'</span>, <span class="st">'red0'</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {}</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> var <span class="kw">in</span> variables_to_test:</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    treatment_data <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][var].dropna()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    control_data <span class="op">=</span> df[df[<span class="st">'control'</span>] <span class="op">==</span> <span class="dv">1</span>][var].dropna()</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># T-test calculations</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    mean_diff <span class="op">=</span> treatment_data.mean() <span class="op">-</span> control_data.mean()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    n_treat <span class="op">=</span> <span class="bu">len</span>(treatment_data)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    n_control <span class="op">=</span> <span class="bu">len</span>(control_data)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    var_treat <span class="op">=</span> treatment_data.var(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    var_control <span class="op">=</span> control_data.var(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    se_diff <span class="op">=</span> ((var_treat <span class="op">/</span> n_treat) <span class="op">+</span> (var_control <span class="op">/</span> n_control)) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    t_stat <span class="op">=</span> mean_diff <span class="op">/</span> se_diff</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    df_denom <span class="op">=</span> ((var_treat <span class="op">/</span> n_treat)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (n_treat <span class="op">-</span> <span class="dv">1</span>)) <span class="op">+</span> ((var_control <span class="op">/</span> n_control)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (n_control <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    df_effective <span class="op">=</span> (var_treat <span class="op">/</span> n_treat <span class="op">+</span> var_control <span class="op">/</span> n_control)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> df_denom</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.t.cdf(<span class="bu">abs</span>(t_stat), df<span class="op">=</span>df_effective))</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Linear regression</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> df[var]</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> sm.add_constant(df[<span class="st">'treatment'</span>])</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> sm.OLS(y, X, missing<span class="op">=</span><span class="st">'drop'</span>).fit()</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    reg_coef <span class="op">=</span> model.params[<span class="st">'treatment'</span>]</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    reg_pval <span class="op">=</span> model.pvalues[<span class="st">'treatment'</span>]</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store results</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    results[var] <span class="op">=</span> {</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Mean (Treatment)'</span>: <span class="bu">round</span>(treatment_data.mean(), <span class="dv">4</span>),</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Mean (Control)'</span>: <span class="bu">round</span>(control_data.mean(), <span class="dv">4</span>),</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Difference'</span>: <span class="bu">round</span>(mean_diff, <span class="dv">4</span>),</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">'t-statistic'</span>: <span class="bu">round</span>(t_stat, <span class="dv">4</span>),</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">'df'</span>: <span class="bu">round</span>(df_effective, <span class="dv">1</span>),</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p-value (t-test)'</span>: <span class="bu">round</span>(p_value, <span class="dv">4</span>),</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Regression Coef'</span>: <span class="bu">round</span>(reg_coef, <span class="dv">4</span>),</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p-value (reg)'</span>: <span class="bu">round</span>(reg_pval, <span class="dv">4</span>)</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame(results).T</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>results_df.index.name <span class="op">=</span> <span class="st">'Variable'</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>results_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean (Treatment)</th>
<th data-quarto-table-cell-role="th">Mean (Control)</th>
<th data-quarto-table-cell-role="th">Difference</th>
<th data-quarto-table-cell-role="th">t-statistic</th>
<th data-quarto-table-cell-role="th">df</th>
<th data-quarto-table-cell-role="th">p-value (t-test)</th>
<th data-quarto-table-cell-role="th">Regression Coef</th>
<th data-quarto-table-cell-role="th">p-value (reg)</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">hpa</td>
<td>59.597198</td>
<td>58.960201</td>
<td>0.6371</td>
<td>0.9704</td>
<td>35913.898438</td>
<td>0.3318</td>
<td>0.6371</td>
<td>0.3451</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>8.035400</td>
<td>8.047300</td>
<td>-0.0120</td>
<td>-0.1108</td>
<td>33326.400000</td>
<td>0.9117</td>
<td>-0.0120</td>
<td>0.9117</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">years</td>
<td>6.078400</td>
<td>6.135900</td>
<td>-0.0575</td>
<td>-1.0909</td>
<td>32400.900000</td>
<td>0.2753</td>
<td>-0.0575</td>
<td>0.2700</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">female</td>
<td>0.275200</td>
<td>0.282700</td>
<td>-0.0075</td>
<td>-1.7535</td>
<td>32450.800000</td>
<td>0.0795</td>
<td>-0.0075</td>
<td>0.0787</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">red0</td>
<td>0.407400</td>
<td>0.398600</td>
<td>0.0087</td>
<td>1.8773</td>
<td>33450.500000</td>
<td>0.0605</td>
<td>0.0087</td>
<td>0.0608</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To assess the integrity of the randomization process employed in Karlan and List’s (2007) field experiment, we conducted a series of balance tests comparing the treatment and control groups on several key pre-treatment variables. The goal of these tests is to verify that the random assignment of fundraising letters resulted in comparable groups with respect to observable characteristics prior to treatment, thereby strengthening the causal interpretation of the experimental findings.</p>
<p>The variables selected for the balance tests closely mirror those presented in Table 1 of the original publication and encompass both donation history and demographic attributes. Specifically, we examine (1) the donor’s highest previous contribution (hpa), (2) the number of prior donations (freq), (3) the number of years since the donor’s initial contribution to the organization (years), (4) an indicator variable for female donors (female), and (5) a binary indicator for residing in a politically conservative (“red”) state as determined by support for George W. Bush in the 2004 U.S. presidential election (red0).</p>
<p>When comparing our calculated group means to those reported in Karlan and List’s Table 1, we find a near-exact match across all variables. In our sample, the mean highest previous contribution is $59.60 for the treatment group and $58.96 for the control group—identical to the values in the published table. Likewise, the average number of prior donations is 8.04 in the treatment group and 8.05 in the control group, with years since initial donation averaging 6.08 and 6.14, respectively. The proportion of female donors is 27.5% in the treatment group and 28.3% in the control group, while the share of donors living in red states is 40.7% versus 39.9% across the two groups. These findings confirm that the implementation of the randomization closely aligns with the authors’ original execution.</p>
<p>To formally test for balance, we employed both two-sample t-tests and simple linear regressions of each covariate on the treatment assignment indicator. In all cases, the resulting p-values were above the conventional 0.05 threshold, indicating no statistically significant differences between the treatment and control groups at the 95% confidence level. The closest results to marginal significance were observed for the female variable (p = 0.080 in the t-test; p = 0.079 in the regression) and the red0 variable (p = 0.060 in the t-test; p = 0.061 in the regression). While these values approach the 10% significance level, they are insufficient to suggest meaningful imbalance and instead support the interpretation that randomization achieved statistical equivalence on observed characteristics.</p>
<p>These balance checks serve a vital role in reinforcing the credibility of the experimental design. As underscored by Karlan and List in their original presentation of Table 1, demonstrating that treatment and control groups are comparable across a range of relevant baseline variables helps rule out confounding factors. Consequently, we can attribute any subsequent differences in donor behavior to the experimental treatments rather than to pre-existing group disparities.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<div id="ab4508a1" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'donated'</span>] <span class="op">=</span> df[<span class="st">'gave'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>donation_rates <span class="op">=</span> df.groupby(<span class="st">'treatment'</span>)[<span class="st">'donated'</span>].mean()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">4</span>))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'donated'</span>] <span class="op">=</span> df[<span class="st">'gave'</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>donation_rates <span class="op">=</span> df.groupby(<span class="st">'treatment'</span>)[<span class="st">'donated'</span>].mean()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">4</span>))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>donation_rates.index, y<span class="op">=</span>donation_rates.values)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>plt.xticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">'Control'</span>, <span class="st">'Treatment'</span>])</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Proportion Who Donated'</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Donation Rates by Treatment Group'</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="bu">max</span>(donation_rates.values) <span class="op">*</span> <span class="fl">1.2</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>treatment_don <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'donated'</span>]</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>control_don <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'donated'</span>]</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>t_stat, p_val <span class="op">=</span> stats.ttest_ind(treatment_don, control_don, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>X_lin <span class="op">=</span> sm.add_constant(df[<span class="st">'treatment'</span>])</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>model_lin <span class="op">=</span> sm.OLS(df[<span class="st">'donated'</span>], X_lin).fit()</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>model_probit <span class="op">=</span> sm.Probit(df[<span class="st">'donated'</span>], X_lin).fit(disp<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a DataFrame to display results in a table</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>results_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Control Group'</span>: [donation_rates[<span class="dv">0</span>]],</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Treatment Group'</span>: [donation_rates[<span class="dv">1</span>]],</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Difference'</span>: [donation_rates[<span class="dv">1</span>] <span class="op">-</span> donation_rates[<span class="dv">0</span>]],</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'t-statistic'</span>: [t_stat],</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value (t-test)'</span>: [p_val],</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Linear Regression Coef'</span>: [model_lin.params[<span class="st">'treatment'</span>]],</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value (regression)'</span>: [model_lin.pvalues[<span class="st">'treatment'</span>]],</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Probit Coef'</span>: [model_probit.params[<span class="st">'treatment'</span>]],</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value (probit)'</span>: [model_probit.pvalues[<span class="st">'treatment'</span>]]</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>results_table <span class="op">=</span> results_table.<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>results_table.index <span class="op">=</span> [<span class="st">'Donation Rate'</span>]</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>results_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 576x384 with 0 Axes&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-4-output-2.png" width="566" height="374" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display" data-execution_count="52">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Control Group</th>
<th data-quarto-table-cell-role="th">Treatment Group</th>
<th data-quarto-table-cell-role="th">Difference</th>
<th data-quarto-table-cell-role="th">t-statistic</th>
<th data-quarto-table-cell-role="th">p-value (t-test)</th>
<th data-quarto-table-cell-role="th">Linear Regression Coef</th>
<th data-quarto-table-cell-role="th">p-value (regression)</th>
<th data-quarto-table-cell-role="th">Probit Coef</th>
<th data-quarto-table-cell-role="th">p-value (probit)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Donation Rate</td>
<td>0.0179</td>
<td>0.022</td>
<td>0.0042</td>
<td>3.2095</td>
<td>0.0013</td>
<td>0.0042</td>
<td>0.0019</td>
<td>0.0868</td>
<td>0.0019</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To evaluate the impact of matching grants on charitable giving, we analyzed the difference in donation rates between individuals who received a standard solicitation letter (control group) and those who received a letter offering a matching grant (treatment group). The results, visualized in Figure 1, show that 1.79% of individuals in the control group made a donation, compared to 2.20% in the treatment group. This initial comparison suggests a positive effect of the matching grant offer on the likelihood of donating.</p>
<p>To assess the statistical significance of this difference, we conducted a two-sample t-test for proportions. The t-statistic was 3.21, with a corresponding p-value of 0.0013, indicating that the increase in donation rates among the treatment group is statistically significant at the 1% level. This result suggests that the observed difference is unlikely to be due to random chance alone.</p>
<p>To further substantiate this finding, we estimated a bivariate linear regression with a binary dependent variable indicating whether a donation was made. The treatment group indicator had a coefficient of 0.0042, which implies a 0.42 percentage point increase in donation likelihood associated with receiving a matching offer. The p-value associated with this coefficient was 0.0019, reaffirming the statistical significance of the treatment effect. The model’s R-squared value, although small (0.00019), is typical for binary outcomes in field settings and highlights that the variation in donations is largely driven by unobserved factors, as expected.</p>
<p>Additionally, we replicated the probit regression reported in Table 3, Column 1 of Karlan and List (2007), where the probability of donating was modeled as a function of treatment status. Our probit estimate of the treatment coefficient was 0.087, with a p-value of 0.0019—closely matching the original study. This replication reinforces the original conclusion that offering a matching grant significantly increases the probability of donation.</p>
<p>Taken together, these results provide robust evidence that matching grants effectively increase charitable giving, even when evaluated using conservative statistical methods. The increase, though modest in magnitude, is statistically significant and practically meaningful, particularly in the context of large-scale fundraising efforts. These findings align with the behavioral insight that individuals are more likely to give when their contributions are perceived to have enhanced impact or when social cues, such as matching gifts, signal urgency or endorsement.</p>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<div id="8342684d" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>treatment_df <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>].copy()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>treatment_df[<span class="st">'ratio1'</span>] <span class="op">=</span> (treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>treatment_df[<span class="st">'ratio2'</span>] <span class="op">=</span> (treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>treatment_df[<span class="st">'ratio3'</span>] <span class="op">=</span> (treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>).astype(<span class="bu">int</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>response_rates <span class="op">=</span> treatment_df.groupby(<span class="st">'ratio'</span>, observed<span class="op">=</span><span class="va">True</span>)[<span class="st">'donated'</span>].mean()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>t1_vs_t2 <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    treatment_df[treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'donated'</span>],</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    treatment_df[treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>][<span class="st">'donated'</span>],</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>t2_vs_t3 <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    treatment_df[treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>][<span class="st">'donated'</span>],</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    treatment_df[treatment_df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>][<span class="st">'donated'</span>],</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>X_ratios <span class="op">=</span> treatment_df[[<span class="st">'ratio1'</span>, <span class="st">'ratio2'</span>, <span class="st">'ratio3'</span>]]</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>model_ratios <span class="op">=</span> sm.OLS(treatment_df[<span class="st">'donated'</span>], X_ratios).fit()</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>coef_1v2 <span class="op">=</span> model_ratios.params[<span class="st">'ratio2'</span>] <span class="op">-</span> model_ratios.params[<span class="st">'ratio1'</span>]</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>coef_2v3 <span class="op">=</span> model_ratios.params[<span class="st">'ratio3'</span>] <span class="op">-</span> model_ratios.params[<span class="st">'ratio2'</span>]</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>vcov <span class="op">=</span> model_ratios.cov_params()</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>se_1v2 <span class="op">=</span> (vcov.loc[<span class="st">'ratio1'</span>, <span class="st">'ratio1'</span>] <span class="op">+</span> vcov.loc[<span class="st">'ratio2'</span>, <span class="st">'ratio2'</span>] <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> vcov.loc[<span class="st">'ratio1'</span>, <span class="st">'ratio2'</span>]) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>se_2v3 <span class="op">=</span> (vcov.loc[<span class="st">'ratio2'</span>, <span class="st">'ratio2'</span>] <span class="op">+</span> vcov.loc[<span class="st">'ratio3'</span>, <span class="st">'ratio3'</span>] <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> vcov.loc[<span class="st">'ratio2'</span>, <span class="st">'ratio3'</span>]) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Match Ratio'</span>: [<span class="st">'1:1'</span>, <span class="st">'2:1'</span>, <span class="st">'3:1'</span>],</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Response Rate'</span>: [response_rates[<span class="dv">1</span>], response_rates[<span class="dv">2</span>], response_rates[<span class="dv">3</span>]],</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Regression Coefficient'</span>: [model_ratios.params[<span class="st">'ratio1'</span>], model_ratios.params[<span class="st">'ratio2'</span>], model_ratios.params[<span class="st">'ratio3'</span>]],</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value'</span>: [model_ratios.pvalues[<span class="st">'ratio1'</span>], model_ratios.pvalues[<span class="st">'ratio2'</span>], model_ratios.pvalues[<span class="st">'ratio3'</span>]]</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Comparison'</span>: [<span class="st">'1:1 vs 2:1'</span>, <span class="st">'2:1 vs 3:1'</span>],</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Difference in Response Rate'</span>: [response_rates[<span class="dv">2</span>] <span class="op">-</span> response_rates[<span class="dv">1</span>], response_rates[<span class="dv">3</span>] <span class="op">-</span> response_rates[<span class="dv">2</span>]],</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">'t-statistic'</span>: [t1_vs_t2.statistic, t2_vs_t3.statistic],</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value'</span>: [t1_vs_t2.pvalue, t2_vs_t3.pvalue],</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Coefficient Difference'</span>: [coef_1v2, coef_2v3],</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Standard Error'</span>: [se_1v2, se_2v3]</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> results_df.<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="op">=</span> comparison_df.<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>results_df.set_index(<span class="st">'Match Ratio'</span>)</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results_df)</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(comparison_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Match Ratio  Response Rate  Regression Coefficient  p-value
0         1:1         0.0207                  0.0207      0.0
1         2:1         0.0226                  0.0226      0.0
2         3:1         0.0227                  0.0227      0.0
   Comparison  Difference in Response Rate  t-statistic  p-value  \
0  1:1 vs 2:1                       0.0019      -0.9650   0.3345   
1  2:1 vs 3:1                       0.0001      -0.0501   0.9600   

   Coefficient Difference  Standard Error  
0                  0.0019           0.002  
1                  0.0001           0.002  </code></pre>
</div>
</div>
<p>To further investigate the effectiveness of different matching grant ratios, we restricted our analysis to individuals in the treatment group and examined variation in donation rates across three matching levels: 1:1, 2:1, and 3:1. The response rates were remarkably similar across groups, with 2.07% of individuals in the 1:1 match group donating, compared to 2.26% in the 2:1 group and 2.27% in the 3:1 group. Although there is a slight upward trend in donation rates as the match ratio increases, the absolute differences are marginal—only 0.19 and 0.01 percentage points between successive levels.</p>
<p>To assess whether these differences are statistically meaningful, we conducted a series of two-sample t-tests comparing the donation rates between match levels. The difference between the 1:1 and 2:1 groups was not statistically significant (p=0.335), nor was the difference between the 2:1 and 3:1 groups (p=0.960). These results provide no evidence that offering a higher match ratio leads to a greater likelihood of donation.</p>
<p>We corroborated these findings using an ordinary least squares (OLS) regression, regressing the binary donation outcome on dummy indicators for each match ratio group. The regression was specified without an intercept so that each coefficient would represent the mean response rate for its respective group. The estimated coefficients were 0.02075 for the 1:1 group, 0.02263 for the 2:1 group, and 0.02273 for the 3:1 group, all statistically significant at the 0.001 level. However, differences between these coefficients were small and statistically indistinguishable. Specifically, the difference between the 2:1 and 1:1 coefficients was 0.00188 (SE = 0.00197), and the difference between the 3:1 and 2:1 coefficients was just 0.00010 (SE = 0.00197). Neither difference is statistically significant, confirming the t-test results.</p>
<p>These findings align with Karlan and List’s original interpretation in their 2007 study. While the presence of a match clearly boosts giving relative to a control condition, increasing the match ratio from 1:1 to 2:1 or 3:1 does not generate additional giving. This suggests that the behavioral mechanism driving increased donations is not necessarily the financial leverage offered by higher match ratios, but rather the psychological or social signal conveyed by the presence of any match offer. The match may function more as a nudge or cue, reinforcing the importance or credibility of the appeal, rather than as a precise price incentive.</p>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<div id="c07256d1" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>X_full <span class="op">=</span> sm.add_constant(df[<span class="st">'treatment'</span>])</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>model_full <span class="op">=</span> sm.OLS(df[<span class="st">'amount'</span>], X_full, missing<span class="op">=</span><span class="st">'drop'</span>).fit()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>donors_df <span class="op">=</span> df[df[<span class="st">'amount'</span>] <span class="op">&gt;</span> <span class="dv">0</span>].copy()</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>X_donors <span class="op">=</span> sm.add_constant(donors_df[<span class="st">'treatment'</span>])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>model_donors <span class="op">=</span> sm.OLS(donors_df[<span class="st">'amount'</span>], X_donors).fit()</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>treatment_donors <span class="op">=</span> donors_df[donors_df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>]</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>control_donors <span class="op">=</span> donors_df[donors_df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>plt.hist(control_donors, bins<span class="op">=</span><span class="dv">30</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>plt.axvline(control_donors.mean(), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Donation Amounts: Control Group'</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Donation Amount'</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>plt.hist(treatment_donors, bins<span class="op">=</span><span class="dv">30</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>plt.axvline(treatment_donors.mean(), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Donation Amounts: Treatment Group'</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Donation Amount'</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>regression_results <span class="op">=</span> pd.DataFrame({</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Model'</span>: [<span class="st">'OLS Full Sample'</span>, <span class="st">'OLS Donors Only'</span>],</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Coefficient'</span>: [model_full.params[<span class="st">'treatment'</span>], model_donors.params[<span class="st">'treatment'</span>]],</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value'</span>: [model_full.pvalues[<span class="st">'treatment'</span>], model_donors.pvalues[<span class="st">'treatment'</span>]]</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>regression_results.set_index(<span class="st">'Model'</span>).<span class="bu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-6-output-1.png" width="950" height="374" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display" data-execution_count="54">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">p-value</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">OLS Full Sample</td>
<td>0.154</td>
<td>0.063</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">OLS Donors Only</td>
<td>-1.668</td>
<td>0.561</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To evaluate the effect of matching grant offers on the amount donated, we conducted a series of ordinary least squares (OLS) regressions and visualized the distribution of donation amounts across treatment conditions. We first estimated a linear model using the full sample, which included both donors and non-donors. The regression specification modeled donation amount as a function of a binary treatment indicator. The estimated coefficient on the treatment variable was $0.154, with a p-value of 0.063. Although this estimate is not statistically significant at the conventional 5% level, it reaches marginal significance at the 10% level, suggesting that offering a matching grant may slightly increase overall donations by increasing participation, rather than the amount given by each donor.</p>
<p>To isolate the intensive margin, whether the treatment affected how much individuals gave once they decided to donate we ran the same regression on a restricted sample of donors only. In this case, the estimated coefficient on the treatment indicator was –$1.67, with a p-value of 0.561. This result indicates that among those who chose to donate, individuals in the treatment group gave slightly less on average than those in the control group. However, the difference is not statistically significant, and the relatively large p-value suggests that this finding is likely attributable to random variation rather than a treatment effect.</p>
<p>Histograms of donation amounts for both the control and treatment groups further illuminate the distributional patterns. As is typical in charitable giving data, both distributions are highly right-skewed, with most donors giving relatively small amounts and a few contributing substantially more. Visual inspection shows little difference between the two groups, with the average donation in each group marked by a red dashed line. The near overlap in mean values visually reinforces the regression results: while the presence of a matching offer may influence whether someone donates, it appears to have little effect on how much they give once they have made the decision to contribute.</p>
<p>Overall, this analysis complements prior findings by reinforcing the notion that matching grants primarily operate on the extensive margin—that is, increasing the likelihood of giving—rather than on the intensive margin, or the size of the gift. This distinction is important for fundraisers: while match offers can broaden donor participation, they may not significantly raise per-donor revenue among those who are already inclined to give.</p>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<div id="e650bbf2" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>p_control <span class="op">=</span> <span class="fl">0.018</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>p_treatment <span class="op">=</span> <span class="fl">0.022</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>n_simulations <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>, <span class="dv">1000</span>]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>sim_results <span class="op">=</span> {}</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n <span class="kw">in</span> sample_sizes:</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    control_samples <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_control, size<span class="op">=</span>(n_simulations, n))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    treatment_samples <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_treatment, size<span class="op">=</span>(n_simulations, n))</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    control_means <span class="op">=</span> control_samples.mean(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    treatment_means <span class="op">=</span> treatment_samples.mean(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    pooled_std <span class="op">=</span> np.sqrt((control_means <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> control_means) <span class="op">/</span> n) <span class="op">+</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                         (treatment_means <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> treatment_means) <span class="op">/</span> n))</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    valid_indices <span class="op">=</span> pooled_std <span class="op">&gt;</span> <span class="dv">0</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    t_stats <span class="op">=</span> np.full(n_simulations, np.nan) </span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    t_stats[valid_indices] <span class="op">=</span> (treatment_means[valid_indices] <span class="op">-</span> control_means[valid_indices]) <span class="op">/</span> pooled_std[valid_indices]</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    sim_results[n] <span class="op">=</span> {</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_control"</span>: np.mean(control_means),</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_treatment"</span>: np.mean(treatment_means),</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_t_statistic"</span>: np.nanmean(t_stats),</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"std_t_statistic"</span>: np.nanstd(t_stats),</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>        <span class="st">"t_statistics"</span>: t_stats</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>sim_results_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sample Size"</span>: sample_sizes,</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Mean (Control)"</span>: [sim_results[n][<span class="st">"mean_control"</span>] <span class="cf">for</span> n <span class="kw">in</span> sample_sizes],</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Mean (Treatment)"</span>: [sim_results[n][<span class="st">"mean_treatment"</span>] <span class="cf">for</span> n <span class="kw">in</span> sample_sizes],</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Mean t-stat"</span>: [sim_results[n][<span class="st">"mean_t_statistic"</span>] <span class="cf">for</span> n <span class="kw">in</span> sample_sizes],</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SD t-stat"</span>: [sim_results[n][<span class="st">"std_t_statistic"</span>] <span class="cf">for</span> n <span class="kw">in</span> sample_sizes]</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>sim_results_df.set_index(<span class="st">"Sample Size"</span>).<span class="bu">round</span>(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="55">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Mean (Control)</th>
<th data-quarto-table-cell-role="th">Mean (Treatment)</th>
<th data-quarto-table-cell-role="th">Mean t-stat</th>
<th data-quarto-table-cell-role="th">SD t-stat</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Sample Size</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">50</td>
<td>0.01797</td>
<td>0.02230</td>
<td>0.16417</td>
<td>1.01288</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">100</td>
<td>0.01792</td>
<td>0.02204</td>
<td>0.20872</td>
<td>0.99637</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">500</td>
<td>0.01799</td>
<td>0.02204</td>
<td>0.45369</td>
<td>1.00300</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1000</td>
<td>0.01800</td>
<td>0.02195</td>
<td>0.62989</td>
<td>0.98994</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="a5a07f3b" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">4</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="dv">500</span>, <span class="dv">1000</span>]):</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    t_stats <span class="op">=</span> sim_results[n][<span class="st">'t_statistics'</span>]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    axs[i].hist(t_stats, bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>, density<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    axs[i].axvline(x<span class="op">=</span>np.mean(t_stats), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Mean t-stat'</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    axs[i].set_title(<span class="ss">f'T-statistics Distribution (n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    axs[i].set_xlabel(<span class="st">'t-statistic'</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    axs[i].set_ylabel(<span class="st">'Density'</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    axs[i].legend()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-8-output-1.png" width="1142" height="374" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To illustrate foundational statistical principles such as the Law of Large Numbers and the Central Limit Theorem within the context of the Karlan and List (2007) experimental design, we conducted a simulation study comparing two groups: a control group with a donation probability of 0.018, and a treatment group with a slightly higher donation probability of 0.022. These probabilities mirror the actual donation rates observed in the original field experiment. We simulated 10,000 random samples for each group across a range of increasing sample sizes—specifically n= 50, 100, 500, and 1,000 and calculated the mean donation rates as well as t-statistics for comparing group means within each simulation iteration.</p>
<p>The results underscore key statistical principles. As sample sizes increased, the simulated group means converged to the true underlying probabilities. For instance, at n=1,000, the average simulated donation rate for the control group was 0.01800, and for the treatment group, 0.02195—nearly identical to their theoretical values. The average t-statistic for n=1,000 was approximately 0.63, with a standard deviation near 0.99, indicating the t-statistic distribution was both centered and scaled appropriately, as expected under the Central Limit Theorem. In contrast, at smaller sample sizes (n=50 and n=100), the t-statistic distributions were unstable, with many values undefined or highly variable due to the small number of binary outcomes and low donation rates. These issues resulted in missing or non-informative summary statistics, highlighting the volatility of inference at small 𝑛.</p>
<p>Visualizations of the t-statistics for n=500 and n=1,000 further reinforce these patterns. The histograms reveal increasingly symmetric, bell-shaped distributions as the sample size grows, with the mean of each distribution marked by a red dashed line. At n=1,000, the distribution closely approximates a standard normal curve, a hallmark of the Central Limit Theorem. The standard deviation of the t-statistic distribution also approaches 1, which is consistent with theoretical expectations for standardized test statistics under the null hypothesis.</p>
<p>These results demonstrate how both the Law of Large Numbers and the Central Limit Theorem manifest in practice. As sample sizes grow, sample means become more accurate estimates of the population parameters (convergence in probability), and the sampling distribution of test statistics approaches a normal distribution, enabling valid inference using tools like the t-test. Conversely, in small samples, randomness dominates, increasing the likelihood of erratic or misleading results. This simulation thus reinforces the importance of sufficient sample size in experimental design and statistical inference—especially when working with low-probability binary outcomes, such as charitable giving.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<div id="e62f3a7e" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>control_draws <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.018</span>, size<span class="op">=</span><span class="dv">100000</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>treatment_draws <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.022</span>, size<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>control_draws_subset <span class="op">=</span> control_draws[:<span class="dv">10000</span>]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>diff_vector <span class="op">=</span> treatment_draws <span class="op">-</span> control_draws_subset</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>cumulative_avg_diff <span class="op">=</span> np.cumsum(diff_vector) <span class="op">/</span> np.arange(<span class="dv">1</span>, <span class="bu">len</span>(diff_vector) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>plt.plot(cumulative_avg_diff, label<span class="op">=</span><span class="st">'Cumulative Average of Differences'</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="fl">0.022</span> <span class="op">-</span> <span class="fl">0.018</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'True Mean Difference (0.004)'</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Law of Large Numbers: Cumulative Average of Differences'</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Number of Simulated Observations'</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Cumulative Average'</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-9-output-1.png" width="758" height="470" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To visually demonstrate the Law of Large Numbers (LLN) in the context of donation behavior, we simulated binary donation outcomes from two Bernoulli distributions. Specifically, we generated 100,000 independent draws from a control group distribution with a probability of success p=0.018 and 10,000 draws from a treatment group distribution with p=0.022. We then computed the difference between each of the first 10,000 matched treatment and control observations and tracked the cumulative average of these differences across the sample. This cumulative average was plotted against the number of simulated observations, with a red dashed line indicating the true mean difference between the two groups (0.022 − 0.018 = 0.004).</p>
<p>The resulting graph illustrates the fundamental property of the LLN. In the early stages of the simulation, the cumulative average of differences fluctuates substantially, reflecting the volatility inherent in small samples. However, as more observations are included, the cumulative average begins to stabilize and gradually converges toward the true population difference of 0.004. This convergence visually affirms the core prediction of the LLN: as the number of independent and identically distributed trials increases, the sample average tends to approach the expected value.</p>
<p>This simulation effectively contextualizes the LLN using a real-world experimental design and underscores why statistical inference becomes more reliable with larger sample sizes. By showing how the empirical difference in donation behavior becomes increasingly stable and reflective of the underlying population parameters, the simulation reinforces both the theoretical importance and practical implications of the LLN in experimental economics and applied statistics.</p>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<div id="13d3c828" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n_replications <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>p_control <span class="op">=</span> <span class="fl">0.018</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>p_treatment <span class="op">=</span> <span class="fl">0.022</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>mean_diffs_by_n <span class="op">=</span> {}</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes):</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    mean_diffs <span class="op">=</span> []</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_replications):</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>        control_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_control, size<span class="op">=</span>n)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>        treatment_sample <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, p_treatment, size<span class="op">=</span>n)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        mean_diff <span class="op">=</span> treatment_sample.mean() <span class="op">-</span> control_sample.mean()</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        mean_diffs.append(mean_diff)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    mean_diffs_by_n[n] <span class="op">=</span> mean_diffs</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axs[i <span class="op">//</span> <span class="dv">2</span>, i <span class="op">%</span> <span class="dv">2</span>]</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    ax.hist(mean_diffs, bins<span class="op">=</span><span class="dv">30</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, density<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span>np.mean(mean_diffs), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Mean Difference'</span>)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, label<span class="op">=</span><span class="st">'Zero'</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'Sample Size = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Average Difference (Treatment - Control)'</span>)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Density'</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    ax.legend()</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/cell-10-output-1.png" width="1142" height="758" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To illustrate the Central Limit Theorem (CLT) in the context of experimental data on charitable giving, we conducted a simulation comparing average donation rates between control and treatment groups drawn from Bernoulli distributions. Specifically, we simulated 1,000 replications at each of four different sample sizes n=50, 200, 500, and 1,000— sing control group probabilities of p=0.018 and treatment group probabilities of p=0.022. In each replication, we calculated the difference in sample means (treatment minus control), resulting in distributions of 1,000 average differences for each sample size.</p>
<p>The histograms of these average differences provide compelling visual evidence for the CLT. At n=50, the distribution is jagged and displays high variability. The value of zero, which represents the null hypothesis of no treatment effect, appears near the center of the distribution due to this noise. At n=200, the distribution becomes more symmetric and begins to resemble a bell-shaped curve, while the sampling mean visibly approaches the true population difference of 0.004. By n=500 and 𝑛=1,000, the distributions exhibit the hallmark shape of the normal distribution: smooth, symmetric, and tightly centered around the expected mean. In these larger samples, the value of zero lies clearly in the tail of the distribution, suggesting that a t-test would likely reject the null hypothesis in favor of a statistically significant treatment effect.</p>
<p>These results vividly demonstrate the predictive power of the CLT. As the sample size increases, the sampling distribution of the difference in sample means converges in shape to the normal distribution, even though the underlying data are binary. This convergence underpins the validity of inferential tools such as the t-test and confidence intervals in empirical work. It also highlights why larger sample sizes enhance statistical power and reduce the risk of Type II error. In sum, this simulation confirms that even in experiments involving binary outcomes like donation behavior, standard statistical inference remains appropriate and robust when sample sizes are sufficiently large.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>